# Generated by Django 5.1.4 on 2024-12-18 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inn', models.CharField(max_length=12, unique=True, verbose_name='ИНН')),
                ('ogrn', models.CharField(max_length=13, unique=True, verbose_name='ОГРН')),
                ('name', models.CharField(max_length=255, verbose_name='Название компании')),
                ('address', models.TextField(verbose_name='Адрес')),
                ('director', models.CharField(blank=True, max_length=255, null=True, verbose_name='Руководитель')),
                ('activity', models.TextField(blank=True, null=True, verbose_name='Вид деятельности')),
                ('registration_date', models.DateField(blank=True, null=True, verbose_name='Дата регистрации')),
                ('status', models.CharField(default='Активна', max_length=50, verbose_name='Статус')),
            ],
        ),
        migrations.DeleteModel(
            name='Client',
        ),
    ]
